### ISSUE TITLE
7_smart_dhx-multiparty-n9.js reverts and fails.

### ISSUE THREAD

**Issue by LucasMSg** [robmuth/smart-dhx#3]
Hello, I'm trying to execute your migrations and tests in Truffle v5.3.14 (core: 5.3.14) with Solidity v0.5.16 (solc-js). 

Migration 7_smart_dhx-multiparty-n9.js reverts and fails. The error occurs in: `let b = await helper.answerBatch(batchClients.map(c => c.address), batchClientsKeys, batchAnswerKeys);` 

Code works fine for a smaller number of client instances, it starts failing with 6 instances. Answering in a loop, in the style of 2_TestMultiPartyDHX.js works as well. 

Any idea what might be happening?

**Comment by robmuth** [comment]
Hi Lucas, if you run the test case migrations locally on Ganache, the default Gas Limit needs to be increased (for example, I increased it to 100,000,000).

As you've already figured, it also works if you call ```answer(...)``` one at a time. The ```answerBatch(...)``` approach with the MigrationsHelper was meant to show how to bundle multiple key exchanges in fewer transactions, but each transaction then requires more Gas.

I hope that works for you.

**Comment by LucasMSg** [comment]
Hi Robert, thank you very much for your answer, it's all clear now. 

In your paper, when you mention the $\sum_{k=1 }^{n}k$ transactions needed for Multi-party SmartDHX, are you referring to its execution with the MigrationHelper?

**Comment by robmuth** [comment]
Yes, that is right, the multi-party implementation uses the ```answerBatch(...)``` approach and therefore requires $\sum_{k=1}^{n}k$ transactions.
